import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function formatJSON(input: string): { result: string; error: string | null } {
  try {
    const parsed = JSON.parse(input);
    return { result: JSON.stringify(parsed, null, 2), error: null };
  } catch (e) {
    return { result: "", error: (e as Error).message };
  }
}

export function formatCSV(input: string): { result: string; error: string | null } {
  try {
    const lines = input.trim().split("\n");
    if (lines.length === 0) return { result: "", error: "Empty input" };

    const result = lines
      .map((line) => {
        const cols = line.split(",").map((c) => c.trim());
        return cols.join(" | ");
      })
      .join("\n");
    return { result, error: null };
  } catch (e) {
    return { result: "", error: (e as Error).message };
  }
}

export function formatXML(input: string): { result: string; error: string | null } {
  try {
    let formatted = "";
    let indent = 0;
    const tab = "  ";

    input
      .replace(/>\s*</g, "><")
      .trim()
      .split(/(?<=>)(?=<)/)
      .forEach((node) => {
        if (node.match(/^<\/\w/)) indent--;
        formatted += `${tab.repeat(Math.max(0, indent))}${node}\n`;
        if (node.match(/^<\w[^/]*[^/]>$/) && !node.includes("</")) indent++;
      });

    return { result: formatted.trim(), error: null };
  } catch (e) {
    return { result: "", error: (e as Error).message };
  }
}

export function computeDiff(
  original: string,
  modified: string
): Array<{ type: "added" | "removed" | "unchanged"; content: string }> {
  const originalLines = original.split("\n");
  const modifiedLines = modified.split("\n");
  const result: Array<{ type: "added" | "removed" | "unchanged"; content: string }> = [];

  const maxLen = Math.max(originalLines.length, modifiedLines.length);

  for (let i = 0; i < maxLen; i++) {
    const origLine = originalLines[i];
    const modLine = modifiedLines[i];

    if (origLine === undefined) {
      result.push({ type: "added", content: modLine });
    } else if (modLine === undefined) {
      result.push({ type: "removed", content: origLine });
    } else if (origLine === modLine) {
      result.push({ type: "unchanged", content: origLine });
    } else {
      result.push({ type: "removed", content: origLine });
      result.push({ type: "added", content: modLine });
    }
  }

  return result;
}

export function generateGitignore(stacks: string[]): string {
  const rules: Record<string, string> = {
    node: `# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
package-lock.json
.npm`,
    python: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
ENV/
build/
dist/
*.egg-info/
.eggs/
*.egg
.pytest_cache/
.coverage
htmlcov/
.tox/
.mypy_cache/`,
    java: `# Java
*.class
*.log
*.jar
*.war
*.ear
*.zip
*.tar.gz
*.rar
target/
.mvn/wrapper/maven-wrapper.jar
.classpath
.project
.settings/
*.iml`,
    react: `# React / Next.js
.next/
out/
build/
.DS_Store
*.pem
.env.local
.env.development.local
.env.test.local
.env.production.local`,
    vue: `# Vue.js
dist/
node_modules/
.env.local
.env.*.local
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.idea/
.vscode/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?`,
    dotnet: `# .NET
*.user
*.suo
.vs/
bin/
obj/
[Dd]ebug/
[Rr]elease/
*.nupkg
*.nuspec
project.lock.json
project.fragment.lock.json
artifacts/`,
    go: `# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
vendor/
go.sum`,
    rust: `# Rust
/target/
Cargo.lock
**/*.rs.bk`,
    docker: `# Docker
.dockerignore
docker-compose.override.yml
*.env`,
    macos: `# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes
.fseventsd
.VolumeIcon.icns
.com.apple.timemachine.donotpresent`,
    windows: `# Windows
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
*.stackdump
[Dd]esktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msix
*.msm
*.msp
*.lnk`,
    env: `# Environment variables
.env
.env.*
!.env.example
!.env.template
secrets.json
credentials.json`,
    vscode: `# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace
.history/`,
    idea: `# JetBrains IDEs
.idea/
*.iml
*.ipr
*.iws
out/
.idea_modules/`,
  };

  const header = `# Generated by DevTools Hub — gitignore generator
# https://devtools-hub.vercel.app
# Stacks: ${stacks.join(", ")}
# Generated: ${new Date().toLocaleDateString("en-US")}

`;

  const content = stacks
    .filter((s) => rules[s])
    .map((s) => rules[s])
    .join("\n\n");

  return header + content;
}
